sonar.projectKey=snap-or-slap_snap-or-slap-mobile
sonar.organization=snap-or-slap
sonar.host.url=https://sonarcloud.io

sonar.sources=src
sonar.tests=src

sonar.test.inclusions=**/__tests__/**/*.test.ts,**/__tests__/**/*.test.tsx

sonar.exclusions=**/node_modules/**,**/coverage/**,**/docs/**

sonar.coverage.exclusions=**/__tests__/**,**/*.test.ts,**/*.test.tsx,**/*.types.ts,**/index.ts,**/data/**,**/mocks/**,src/test-utils/**,jest.config.js,jest.setup.ts,src/design-system/**,src/navigation/**,src/services/**,src/shared/**,src/store/**,src/app/AppNavigator.tsx,src/app/RootLayout.tsx

sonar.javascript.lcov.reportPaths=coverage/lcov.info