sonar.projectKey=<PROJECT_KEY_TU_SONARCLOUD>
sonar.organization=<ORGANIZATION_TU_SONARCLOUD>
sonar.host.url=https://sonarcloud.io

sonar.sources=src
sonar.tests=src

sonar.test.inclusions=**/__tests__/**/*.test.ts,**/__tests__/**/*.test.tsx

sonar.exclusions=**/node_modules/**,**/coverage/**,**/docs/**
sonar.coverage.exclusions=**/__tests__/**,**/*.types.ts,**/index.ts,**/data/**,**/mocks/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info